#!/bin/sh
### BEGIN INIT INFO
# Provides:          config_mime
# Required-Start:
# Required-Stop:
# Default-Start: 3
# Default-Stop:
# Short-Description: config_mime
# Description:
### END INIT INFO
. /lib/lsb/init-functions
case "$1" in
  start)
    log_daemon_msg "mime_config init"
    sudo update-mime-database /usr/share/mime &&
	sudo /usr/lib/arm-linux-gnueabihf/gdk-pixbuf-2.0/gdk-pixbuf-query-loaders --update-cache &&
	sudo raspi-config nonint do_ssh 0 &&
    rm /etc/init.d/config_mime &&
    log_end_msg $?
    ;;
  *)
    echo "Usage: $0 start" >&2
    exit 3
    ;;
esac
